//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configurate {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class ExpConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static ExpConfig defaultInstance = ((ExpConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ExpConfig())));
        
        public static ExpConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string PriorytyQuestions {
            get {
                return ((string)(this["PriorytyQuestions"]));
            }
            set {
                this["PriorytyQuestions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double MinProbalityQuestion {
            get {
                return ((double)(this["MinProbalityQuestion"]));
            }
            set {
                this["MinProbalityQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MinGetQuestionMaxProbality {
            get {
                return ((int)(this["MinGetQuestionMaxProbality"]));
            }
            set {
                this["MinGetQuestionMaxProbality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int QuantityAttempt {
            get {
                return ((int)(this["QuantityAttempt"]));
            }
            set {
                this["QuantityAttempt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(LocalDb)\\MSSQLLocalDB;initial catalog=ExpertHeros;integrated security=True;Multi" +
            "pleActiveResultSets=True; Connect Timeout = 10; App=EntityFramework")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dictionary1.xaml")]
        public string Thema {
            get {
                return ((string)(this["Thema"]));
            }
            set {
                this["Thema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FullscreanWinow {
            get {
                return ((int)(this["FullscreanWinow"]));
            }
            set {
                this["FullscreanWinow"] = value;
            }
        }
    }
}
